/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "CLK_aliases.h"
#include "CLK.h"
#include "SS_aliases.h"
#include "SS.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "D_C_aliases.h"
#include "D_C.h"
#include "Reset_aliases.h"
#include "Reset.h"
#include "Clock.h"
#include "VDAC8_DS.h"
#include "Pin_DS_aliases.h"
#include "Pin_DS.h"
#include "VDAC8_GS.h"
#include "Pin_GS_aliases.h"
#include "Pin_GS.h"
#include "ADC_SAR_1.h"
#include "Pin_ID_aliases.h"
#include "Pin_ID.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "scl_aliases.h"
#include "scl.h"
#include "sda_aliases.h"
#include "sda.h"
#include "isr.h"
#include "IRQ_aliases.h"
#include "IRQ.h"
#include "emFile_1.h"
#include "Pin_DS_P_aliases.h"
#include "Pin_DS_P.h"
#include "Pin_GS_P_aliases.h"
#include "Pin_GS_P.h"
#include "Pin_ID_P_aliases.h"
#include "Pin_ID_P.h"
#include "AMux_1.h"
#include "AMux_3.h"
#include "AMux_2.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "emFile_1_SPI0.h"
#include "emFile_1_SPI0_PVT.h"
#include "emFile_1_mosi0_aliases.h"
#include "emFile_1_mosi0.h"
#include "emFile_1_Clock_1.h"
#include "emFile_1_miso0_aliases.h"
#include "emFile_1_miso0.h"
#include "emFile_1_sclk0_aliases.h"
#include "emFile_1_sclk0.h"
#include "emFile_1_SPI0_CS_aliases.h"
#include "emFile_1_SPI0_CS.h"
#include "cy_em_eeprom.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

